/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mini_projet;

import Connection.ConnexionBd;
import Connection.SalEmployee;
import Connection.TempsEmployee;
import Modeles.GesSalaire;
import Modeles.GesTemps;
import Modeles.etudiant;
import java.awt.Image;
import java.awt.MouseInfo;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import static mini_projet.Utilisateurs.id2;

/**
 *
 * @author BoniP
 */
public class gesTempSal extends javax.swing.JFrame {

    int idcli;
    public gesTempSal() {
        
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    public gesTempSal(int id) {
        this.idcli = id;
        
        initComponents();
        this.setLocationRelativeTo(null);
        client(idcli);
        getTemp();
        getTabSal();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        imgEmp = new javax.swing.JLabel();
        employe = new javax.swing.JLabel();
        labexit = new javax.swing.JLabel();
        labmoin = new javax.swing.JLabel();
        npEmp = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        Suptemp = new javax.swing.JButton();
        Addtemp = new javax.swing.JButton();
        tempdate = new javax.swing.JTextField();
        txtpsort = new javax.swing.JTextField();
        txtentry = new javax.swing.JTextField();
        labsort = new javax.swing.JLabel();
        labdate = new javax.swing.JLabel();
        labentry = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableTemp = new javax.swing.JTable();
        vidertemp = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabsalairs = new javax.swing.JTable();
        txtsal = new javax.swing.JTextField();
        textpmt = new javax.swing.JTextField();
        datesal = new javax.swing.JTextField();
        Supsal = new javax.swing.JButton();
        Addssal = new javax.swing.JButton();
        labsal = new javax.swing.JLabel();
        labdates = new javax.swing.JLabel();
        labpmt = new javax.swing.JLabel();
        viderSal = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setBackground(new java.awt.Color(0, 51, 51));
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 153, 51));

        imgEmp.setBackground(new java.awt.Color(0, 102, 102));
        imgEmp.setForeground(new java.awt.Color(204, 204, 255));
        imgEmp.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        employe.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        employe.setForeground(new java.awt.Color(0, 102, 102));
        employe.setText("Gestion employeés");

        labexit.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        labexit.setText(" X");
        labexit.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        labexit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        labexit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labexitMouseClicked(evt);
            }
        });

        labmoin.setFont(new java.awt.Font("Tw Cen MT", 0, 36)); // NOI18N
        labmoin.setText(" -");
        labmoin.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        labmoin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labmoinMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                labmoinMousePressed(evt);
            }
        });

        npEmp.setBackground(new java.awt.Color(0, 51, 51));
        npEmp.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        npEmp.setForeground(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(employe, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(npEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(imgEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addComponent(labmoin, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labexit, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(employe, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(npEmp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(19, 19, 19))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(labmoin, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(labexit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
            .addComponent(imgEmp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));
        jPanel1.setToolTipText("");

        Suptemp.setText("Supprimer");
        Suptemp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SuptempActionPerformed(evt);
            }
        });

        Addtemp.setText("Ajouter");
        Addtemp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddtempActionPerformed(evt);
            }
        });

        txtentry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtentryActionPerformed(evt);
            }
        });

        labsort.setForeground(new java.awt.Color(255, 255, 255));
        labsort.setText("Temp de sortie");

        labdate.setForeground(new java.awt.Color(255, 255, 255));
        labdate.setText("Date ");

        labentry.setForeground(new java.awt.Color(255, 255, 255));
        labentry.setText("Temp d'entrer");

        tableTemp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Temp entrer", "Temp sortie", "Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableTemp);

        vidertemp.setText("vider");
        vidertemp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vidertempActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Addtemp, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(labentry, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                            .addComponent(labsort, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Suptemp, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(vidertemp, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtentry, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                                .addComponent(txtpsort)
                                .addComponent(tempdate)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 136, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 552, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labentry, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtentry, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labsort, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtpsort, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labdate, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tempdate, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Suptemp, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Addtemp, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(vidertemp, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(0, 51, 51));

        tabsalairs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Salaire", "Paiement", "Le reste", "La date"
            }
        ));
        jScrollPane2.setViewportView(tabsalairs);

        Supsal.setText("Supprimer");
        Supsal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SupsalActionPerformed(evt);
            }
        });

        Addssal.setText("Ajouter");
        Addssal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddssalActionPerformed(evt);
            }
        });

        labsal.setForeground(new java.awt.Color(255, 255, 255));
        labsal.setText("Salaire de ce mois");

        labdates.setForeground(new java.awt.Color(255, 255, 255));
        labdates.setText("Date");

        labpmt.setForeground(new java.awt.Color(255, 255, 255));
        labpmt.setText("Paiement");

        viderSal.setText("vider");
        viderSal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viderSalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labdates, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labpmt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(Addssal, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 16, Short.MAX_VALUE))
                    .addComponent(labsal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtsal, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textpmt, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(datesal, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(Supsal, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(viderSal, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 137, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 551, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labsal, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtsal, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textpmt, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labpmt, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(datesal, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labdates, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(52, 52, 52)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Supsal, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Addssal, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(viderSal, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(37, 37, 37)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void labexitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labexitMouseClicked
        this.setVisible(false);
    }//GEN-LAST:event_labexitMouseClicked

    private void labmoinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labmoinMouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_labmoinMouseClicked

    private void SuptempActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SuptempActionPerformed
     if(JOptionPane.showConfirmDialog(null,"Confirmer la supprission d'une date", "Supprission",JOptionPane.YES_NO_OPTION)==JOptionPane.OK_OPTION){
         
           int ligne= tableTemp.getSelectedRow();
          
           String tmpEntr = (String)tableTemp.getModel().getValueAt(ligne,0);
           String tmpSort = (String)tableTemp.getModel().getValueAt(ligne,1);
           String tmpDate = (String)tableTemp.getModel().getValueAt(ligne,2);
           
           GesTemps gs = new GesTemps(idcli,tmpEntr,tmpSort,tmpDate);
           new TempsEmployee().deleteTemp(gs);
           getTemp();
       }
    }//GEN-LAST:event_SuptempActionPerformed

    private void txtentryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtentryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtentryActionPerformed

    private void labmoinMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labmoinMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_labmoinMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        setLocation(MouseInfo.getPointerInfo().getLocation());
    }//GEN-LAST:event_formMouseDragged

    private void vidertempActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vidertempActionPerformed
       if(JOptionPane.showConfirmDialog(null,"Confirmer la supprission du tableau ", "Vider",JOptionPane.YES_NO_OPTION)==JOptionPane.OK_OPTION){
         
           new TempsEmployee().vider(idcli);
           getTemp();
       }
    }//GEN-LAST:event_vidertempActionPerformed

    private void AddtempActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddtempActionPerformed
        
        String tmpEntr = txtentry.getText();
        String tmpSort = txtpsort.getText();
        String tmpdate = tempdate.getText();
        
        if(tmpEntr.equals("")||tmpSort.equals("")||tmpdate.equals("")){
            JOptionPane.showMessageDialog(null,"Un champ ou plus vide, svp remplir tous les champs");
        }
        else{
          GesTemps gs = new GesTemps(idcli,tmpEntr,tmpSort,tmpdate);
          new TempsEmployee().addTemps(gs);
          getTemp();
          
        }
    }//GEN-LAST:event_AddtempActionPerformed

    private void AddssalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddssalActionPerformed
        
        String sal = txtsal.getText();
        String peim = textpmt.getText();
        String saldate = datesal.getText();
        if(sal.equals("")||peim.equals("")||saldate.equals("")){
            JOptionPane.showMessageDialog(null,"Un champ ou plus vide, svp remplir tous les champs");
        }else{
        try{
        Double salMois = Double.parseDouble(sal);
        Double salPeim = Double.parseDouble(peim);
        Double reste = salMois - salPeim ;  
        
        GesSalaire gs = new GesSalaire(idcli,salMois,salPeim,reste,saldate);
        new SalEmployee().addSal(gs);
        getTabSal();
        
        }catch(NumberFormatException e){
           JOptionPane.showMessageDialog(null,"Invalid number, Salaire devrait être contient une valeurs numérique");
         
         }
        
        }
    }//GEN-LAST:event_AddssalActionPerformed

    private void SupsalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SupsalActionPerformed
        
        if(JOptionPane.showConfirmDialog(null,"Confirmer la supprission d'une date", "Supprission",JOptionPane.YES_NO_OPTION)==JOptionPane.OK_OPTION){
        
           int ligne= tabsalairs.getSelectedRow(); 
           String dateSup = (String)tabsalairs.getModel().getValueAt(ligne,3);
           
           new SalEmployee().suppSal(idcli, dateSup);
           
        }
    }//GEN-LAST:event_SupsalActionPerformed

    private void viderSalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viderSalActionPerformed
        if(JOptionPane.showConfirmDialog(null,"Confirmer la supprission d'une date", "Supprission",JOptionPane.YES_NO_OPTION)==JOptionPane.OK_OPTION){
       
           new SalEmployee().vider(idcli);
           
        }
    }//GEN-LAST:event_viderSalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(gesTempSal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(gesTempSal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(gesTempSal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(gesTempSal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new gesTempSal().setVisible(true);
            }
        });
    } 
    
    public void getTemp(){
    
        TempsEmployee tmpServ = new TempsEmployee();
        ArrayList<GesTemps> tmpEmp = tmpServ.getTable(idcli);
        
        DefaultTableModel mod= (DefaultTableModel)tableTemp.getModel();
        Object[] row = new Object[3];
        mod.setRowCount(0);
        for (int i=0; i<tmpEmp.size();i++){
      
            row[0] = tmpEmp.get(i).getTempsEntry();
            row[1] = tmpEmp.get(i).getTempsSortie();
            row[2] = tmpEmp.get(i).getDate();
            mod.addRow(row);
       
        }
    }
    
    public void getTabSal(){
    
        SalEmployee salServ = new SalEmployee();
        ArrayList<GesSalaire> salEmp = salServ.getListSal(idcli);
        
        DefaultTableModel mod2= (DefaultTableModel)tabsalairs.getModel();
        Object[] row2 = new Object[4];
        mod2.setRowCount(0);
        for (int i=0; i<salEmp.size();i++){
      
            row2[0] = salEmp.get(i).getSalaire();
            row2[1] = salEmp.get(i).getPaiement();
            row2[2] = salEmp.get(i).getReste();
            row2[3] = salEmp.get(i).getDateModif();
            mod2.addRow(row2);
       
        }
    }
    
    public void client(int idc){
        
        try {
            Connection cns = ConnexionBd.Connecter();
            Statement  st;
            ResultSet rst;
            st = cns.createStatement();
            
            rst = st.executeQuery("SELECT * FROM employee WHERE id ="+idcli);
            if(rst.next()){
            etudiant clt = new etudiant(rst.getInt("id"),rst.getString("nom"),rst.getString("prenom"),rst.getInt("salaire"),rst.getString("sexe"),rst.getString("email"));
            
            npEmp.setText(clt.getNom()+" "+clt.getPrenom());
            
            byte[] img = rst.getBytes("image");
            ImageIcon image = new ImageIcon(img);
            Image myImg = image.getImage().getScaledInstance(imgEmp.getWidth(), imgEmp.getHeight(),Image.SCALE_SMOOTH);
            ImageIcon Fimg = new ImageIcon(myImg);
            
             imgEmp.setIcon(Fimg);
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(gesTempSal.class.getName()).log(Level.SEVERE, null, ex);
        }
    
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Addssal;
    private javax.swing.JButton Addtemp;
    private javax.swing.JButton Supsal;
    private javax.swing.JButton Suptemp;
    private javax.swing.JTextField datesal;
    private javax.swing.JLabel employe;
    private javax.swing.JLabel imgEmp;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labdate;
    private javax.swing.JLabel labdates;
    private javax.swing.JLabel labentry;
    private javax.swing.JLabel labexit;
    private javax.swing.JLabel labmoin;
    private javax.swing.JLabel labpmt;
    private javax.swing.JLabel labsal;
    private javax.swing.JLabel labsort;
    private javax.swing.JLabel npEmp;
    private javax.swing.JTable tableTemp;
    private javax.swing.JTable tabsalairs;
    private javax.swing.JTextField tempdate;
    private javax.swing.JTextField textpmt;
    private javax.swing.JTextField txtentry;
    private javax.swing.JTextField txtpsort;
    private javax.swing.JTextField txtsal;
    private javax.swing.JButton viderSal;
    private javax.swing.JButton vidertemp;
    // End of variables declaration//GEN-END:variables
}
